=== SoftwareAG/webmethods-opencaf-showcase/build/classes/caf/war/wm_opencaf_showcase/topicList.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.softwareag/wm_mws_docs/topicList" xmlns:tns="http://www.softwareag/wm_mws_docs/topicList" elementFormDefault="qualified">

    <element name="topics" type="tns:topicsType"/>

    <complexType name="topicsType">
        <sequence>
            <element name="topic" type="tns:topicType" minOccurs="0" maxOccurs="unbounded"/>
        </sequence>
    </complexType>

    <complexType name="topicType">
    	<sequence>
    		<element name="href" type="string" minOccurs="0"/>
    		<element name="displayName" type="string"/>
    		<element name="description" type="string"/>
            <element name="topic" type="tns:topicType" minOccurs="0" maxOccurs="unbounded"/>
    	</sequence>
    </complexType>
</schema>

=== SoftwareAG/webmethods-opencaf-showcase/build/classes/caf/war/wm_opencaf_showcase/topicList.xml
<topics xmlns="http://www.softwareag/wm_mws_docs/topicList"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.softwareag/wm_mws_docs/topicList topicList.xsd ">

	<topic>
		<displayName>UI Tags</displayName>
		<description></description>

		<topic>
			<href>http://docs.oracle.com/javaee/7/javaserverfaces/2.2/vdldocs/facelets/</href>
			<displayName>JSF Standard Tags</displayName>
			<description>Tags that are provided by the JSF standard</description>

			<topic>
				<displayName>c</displayName>
				<description>JSTL core tags</description>

				<topic>
					<href>controls/c/catch.xhtml</href>
					<displayName>catch</displayName>
					<description>Catches any Throwable that occurs in its body</description>
				</topic>
				<topic>
					<href>controls/c/choose.xhtml</href>
					<displayName>choose</displayName>
					<description>Conditional processing of its body for multiple choices</description>
				</topic>
				<topic>
					<href>controls/c/if.xhtml</href>
					<displayName>if</displayName>
					<description>Conditional processing of its body</description>
				</topic>
				<topic>
					<href>controls/c/forEach.xhtml</href>
					<displayName>forEach</displayName>
					<description>Loop through each item in a list</description>
				</topic>
				<topic>
					<href>controls/c/otherwise.xhtml</href>
					<displayName>otherwise</displayName>
					<description>Used with c:choose for conditional processing of its body</description>
				</topic>
				<topic>
					<href>controls/c/set.xhtml</href>
					<displayName>set</displayName>
					<description>Used to set the result of an expression evaluation to a variable</description>
				</topic>
				<topic>
					<href>controls/c/when.xhtml</href>
					<displayName>when</displayName>
					<description>Used with c:choose for conditional processing of its body</description>
				</topic>
			</topic>
			<topic>
				<displayName>fn</displayName>
				<description>JSTL EL functions</description>
				<topic>
					<href>controls/fn/el_functions.xhtml</href>
					<displayName>JSTL EL Functions</displayName>
					<description>JSTL EL functions</description>
				</topic>
			</topic>

			<topic>
				<displayName>f</displayName>
				<description>Standard tags that are independent of any particular RenderKit</description>

				<topic>
					<href>controls/f/actionListener.xhtml</href>
					<displayName>actionListener</displayName>
					<description>Action Listener for Command Controls</description>
				</topic>
				<topic>
					<href>controls/f/ajax.xhtml</href>
					<displayName>ajax</displayName>
					<description>AJAX Partial Page Refresh</description>
				</topic>
				<topic>
					<href>controls/f/attribute.xhtml</href>
					<displayName>attribute</displayName>
					<description>Specify an attribute for the parent component</description>
				</topic>
				<topic>
					<href>controls/f/attributes.xhtml</href>
					<displayName>attributes</displayName>
					<description>Specify map of attributes for the parent component</description>
				</topic>
				<topic>
					<href>controls/f/passThroughAttribute.xhtml</href>
					<displayName>passThroughAttribute</displayName>
					<description>Passthrough an attribute to the rendered html element</description>
				</topic>
				<topic>
					<href>controls/f/passThroughAttributes.xhtml</href>
					<displayName>passThroughAttributes</displayName>
					<description>Passthrough an map of attributes to the rendered html element</description>
				</topic>
				<topic>
					<href>controls/f/converter.xhtml</href>
					<displayName>converter</displayName>
					<description>Convert input to/from an object using converterId</description>
				</topic>
				<topic>
					<href>controls/f/convertDateTime.xhtml</href>
					<displayName>convertDateTime</displayName>
					<description>Convert input to/from a Date/Time</description>
				</topic>
				<topic>
					<href>controls/f/convertNumber.xhtml</href>
					<displayName>convertNumber</displayName>
					<description>Convert input to/from a number</description>
				</topic>
				<topic>
					<href>controls/f/event.xhtml</href>
					<displayName>event</displayName>
					<description>Installs ComponentSystemEventListener instances on a component</description>
				</topic>
				<topic>
					<href>controls/f/facet.xhtml</href>
					<displayName>facet</displayName>
					<description>Register a named facet on the closest parent component</description>
				</topic>
				<topic>
					<href>controls/f/loadBundle.xhtml</href>
					<displayName>loadBundle</displayName>
					<description>Load Resource Bundle</description>
				</topic>
				<topic>
					<href>controls/f/metadata.xhtml?meta=helloMetaData</href>
					<displayName>metadata</displayName>
					<description>Declare the metadata facet for this view</description>
				</topic>
				<topic>
					<href>controls/f/param.xhtml</href>
					<displayName>param</displayName>
					<description>Add a child UIParameter component to the closest parent</description>
				</topic>
				<topic>
					<href>controls/f/phaseListener.xhtml</href>
					<displayName>phaseListener</displayName>
					<description>Phase Listener</description>
				</topic>
				<topic>
					<href>controls/f/selectItem.xhtml</href>
					<displayName>selectItem</displayName>
					<description>A single option for a multi-select control</description>
				</topic>
				<topic>
					<href>controls/f/selectItems.xhtml</href>
					<displayName>selectItems</displayName>
					<description>A collection of options for a multi-select control</description>
				</topic>
				<topic>
					<href>controls/f/setPropertyActionListener.xhtml</href>
					<displayName>setPropertyActionListener</displayName>
					<description>Set Property Action Listener for Command Controls</description>
				</topic>
				<topic>
					<href>controls/f/subview.xhtml</href>
					<displayName>subview</displayName>
					<description>Subview naming container</description>
				</topic>
				<topic>
					<href>controls/f/validateDoubleRange.xhtml</href>
					<displayName>validateDoubleRange</displayName>
					<description>Validate a double input is in a range</description>
				</topic>
				<topic>
					<href>controls/f/validateLength.xhtml</href>
					<displayName>validateLength</displayName>
					<description>Validate input has a specified length</description>
				</topic>
				<topic>
					<href>controls/f/validateLongRange.xhtml</href>
					<displayName>validateLongRange</displayName>
					<description>Validate a long input is in a range</description>
				</topic>
				<topic>
					<href>controls/f/validateBean.xhtml</href>
					<displayName>validateBean</displayName>
					<description>Validate using annotations on the bound fields</description>
				</topic>
				<topic>
					<href>controls/f/validateRegex.xhtml</href>
					<displayName>validateRegex</displayName>
					<description>Validate with a regular expression pattern</description>
				</topic>
				<topic>
					<href>controls/f/validateRequired.xhtml</href>
					<displayName>validateRequired</displayName>
					<description>Validate required input</description>
				</topic>
				<topic>
					<href>controls/f/validator.xhtml</href>
					<displayName>validator</displayName>
					<description>Validator via a binding or validatorId</description>
				</topic>
				<topic>
					<href>controls/f/valueChangeListener.xhtml</href>
					<displayName>valueChangeListener</displayName>
					<description>Listener for value changes to an input control</description>
				</topic>
				<topic>
					<href>controls/f/verbatim.xhtml</href>
					<displayName>verbatim</displayName>
					<description>Render children without any changes</description>
				</topic>
				<topic>
					<!-- <href>controls/f/view.xhtml</href> -->
					<displayName>view</displayName>
					<description>Root of components tree</description>
				</topic>
				<topic>
					<href>controls/f/viewParam.xhtml</href>
					<displayName>viewParam</displayName>
					<description>UIViewParam used inside the metadata facet of a view</description>
				</topic>
				<topic>
					<href>controls/f/viewAction.xhtml</href>
					<displayName>viewAction</displayName>
					<description>Action to invoke during one of the JSF lifecycle phases</description>
				</topic>
				<topic>
					<href>controls/f/resetValues.xhtml</href>
					<displayName>resetValues</displayName>
					<description>Reset Values of an Input control during a command action</description>
				</topic>
			</topic>
			<topic>
				<displayName>h</displayName>
				<description>Standard tags for the HTML RenderKit</description>


				<!-- <topic> -->
				<!-- <href>controls/h/body.xhtml</href> -->
				<!-- <displayName>body</displayName> -->
				<!-- <description>Body</description> -->
				<!-- </topic> -->
				<topic>
					<href>controls/h/button.xhtml</href>
					<displayName>button</displayName>
					<description>Button</description>
				</topic>

				<topic>
					<href>controls/h/commandButton.xhtml</href>
					<displayName>commandButton</displayName>
					<description>Button: submit, reset, or pushbutton.</description>
				</topic>
				<topic>
					<href>controls/h/commandLink.xhtml</href>
					<displayName>commandLink</displayName>
					<description>Link that acts like a pushbutton</description>
				</topic>

				<topic>
					<href>controls/h/form.xhtml</href>
					<displayName>form</displayName>
					<description>HTML Form</description>
				</topic>
				<topic>
					<href>controls/h/graphicImage.xhtml</href>
					<displayName>graphicImage</displayName>
					<description>Displays an image</description>
				</topic>
				<!-- <topic> -->
				<!-- <href>controls/h/head.xhtml</href> -->
				<!-- <displayName>head</displayName> -->
				<!-- <description>Head</description> -->
				<!-- </topic> -->
				<topic>
					<href>controls/h/inputFile.xhtml</href>
					<displayName>inputFile</displayName>
					<description>Input File</description>
				</topic>
				<topic>
